# Generated by Django 5.1.4 on 2025-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='mots_cles',
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
