# Generated by Django 5.1.4 on 2025-02-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_offreemploi_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Entretien planifié', 'Entretien planifié'), ('Refusée', 'Refusée')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fichier',
            field=models.FileField(upload_to='media/cvs/'),
        ),
    ]
