# Generated by Django 5.1.4 on 2025-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_nom_customuser_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='hideSalary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='negociable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_emploi',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance'), ('Temporaire', 'Temporaire')], default='CDI', max_length=20),
        ),
    ]
